export interface Preprocessed {
  EMP_CODIGO: number;
  REFERENCIA: string;
  COD_GRUPO: number;
  COD_SETOR_COMERCIAL: number;
  NUM_QUADRA: number;
  COD_ROTA_LEITURA: number;
  MATRICULA: number;
  SEQ_RESPONSAVEL: number;
  ECO_RESIDENCIAL: number;
  ECO_COMERCIAL: number;
  ECO_INDUSTRIAL: number;
  ECO_PUBLICA: number;
  ECO_OUTRAS: number;
  LTR_ATUAL: number;
  LTR_COLETADA: number;
  DAT_LEITURA: string;
  DIAS_LEITURA: number;
  CONS_MEDIDO: number;
  DSC_OCORRENCIA: string;
  COD_LEITURA_INF_1: number;
  COD_LEITURA_INF_2: number;
  COD_LEITURA_INF_3: number;
  HORA_LEITURA: string;
  DSC_SIMULTANEA: string;
  VOLUME_ESTIMADO: number;
  VOLUME_ESTIMADO_ACUM: number;
  COD_LEITURA_INT: number;
  STA_TROCA: string;
  STA_ACEITA_LEITURA: string;
  COD_LATITUDE: number;
  COD_LONGITUDE: number;
  CATEGORIA_COMERCIAL: number;
  CATEGORIA_INDUSTRIAL: number;
  CATEGORIA: string;
  CATEGORIA_PUBLICA: number;
  CATEGORIA_RESIDENCIAL: number;
  SUB_CATEGORIA_COMERCIAL: number;
  SUB_CATEGORIA_INDUSTRIAL: number;
  "SUB_CATEGORIA_PUB. MUNICIPAL": number;
  SUB_CATEGORIA_PUBLICA: number;
  "SUB_CATEGORIA_RES. INDUBRASIL": number;
  "SUB_CATEGORIA_RES. SOCIAL": number;
  SUB_CATEGORIA_RESIDENCIAL: number;
  "TIPO_LIGACAO_Consumo Fixo": number;
  TIPO_LIGACAO_Hidrometrado: number;
  "EXCECAO_Faturar Volume Limite": number;
  "EXCECAO_Faturar apenas o Excesso": number;
  "EXCECAO_Faturar até o Limite": number;
  "EXCECAO_Isento Agua e Esgoto": number;
  "EXCECAO_Isento Esgoto": number;
  EXCECAO_Normal: number;
  FATURADO_MEDIA_Desconhecido: number;
  FATURADO_MEDIA_MEDIA: number;
  FRAUDE: number;
  TIPO_LIGACAO: string;
}
